package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "delim",
    srcs = ["delim.cc"],
    hdrs = ["delim.h"],
    deps = [
        "//base",
        "@com_google_protobuf//:protobuf",
    ],
)

cc_library(
    name = "text",
    srcs = ["text.cc"],
    hdrs = ["text.h"],
    deps = [
        "//base",
        "@com_google_protobuf//:protobuf",
    ],
)
